// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// eslint-disable-next-line import/no-extraneous-dependencies
const { defineConfig } = require("prisma/config");

require("dotenv").config();

module.exports = defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations"
  },
  datasource: {
    url: process.env.DATABASE_URL
  }
});
